// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2hx_IR6q_ldq9R2MmazJhWAAtEb1iebc',
    appId: '1:343683560727:web:638a14eedd671c99793352',
    messagingSenderId: '343683560727',
    projectId: 'projeto-flutter-86f90',
    authDomain: 'projeto-flutter-86f90.firebaseapp.com',
    storageBucket: 'projeto-flutter-86f90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh34p1ZOVai35QBs2fsdRReiIFa9Hyz7I',
    appId: '1:343683560727:android:c78820a3e57586af793352',
    messagingSenderId: '343683560727',
    projectId: 'projeto-flutter-86f90',
    storageBucket: 'projeto-flutter-86f90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBicUgnCG1p0gIgMGghrk4WhH9mYUbWME0',
    appId: '1:343683560727:ios:c58e1df7cbde9954793352',
    messagingSenderId: '343683560727',
    projectId: 'projeto-flutter-86f90',
    storageBucket: 'projeto-flutter-86f90.appspot.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBicUgnCG1p0gIgMGghrk4WhH9mYUbWME0',
    appId: '1:343683560727:ios:c58e1df7cbde9954793352',
    messagingSenderId: '343683560727',
    projectId: 'projeto-flutter-86f90',
    storageBucket: 'projeto-flutter-86f90.appspot.com',
    iosBundleId: 'com.example.projetoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2hx_IR6q_ldq9R2MmazJhWAAtEb1iebc',
    appId: '1:343683560727:web:988fb77f5db19e26793352',
    messagingSenderId: '343683560727',
    projectId: 'projeto-flutter-86f90',
    authDomain: 'projeto-flutter-86f90.firebaseapp.com',
    storageBucket: 'projeto-flutter-86f90.appspot.com',
  );
}
